services:
  spotify-playlists-as-code:
    extends:
      file: docker-compose.common.yml
      service: spotify-playlists-as-code
    ports:
      - 9229:9229
      - 5173:5173
    command: follow:debug
