name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: spotify-api-token

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          file: ./spotify-playlists-as-code/Dockerfile
          context: ./spotify-playlists-as-code
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true

      - name: Check formatting
        run: docker run spac format:check

      - name: Lint
        run: docker run spac lint

      - name: Create refresh token
        run: echo ${REFRESH_TOKEN} > ./spotify-playlists-as-code/data/tokens/refresh_token
        env:
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}

      - name: Run healthcheck
        run: docker compose run spac healthcheck
        env:
          CLIENT_ID: ${{ vars.CLIENT_ID }}

      - name: Update refresh token secret
        if: always()
        run: gh secret set REFRESH_TOKEN < ./spotify-playlists-as-code/data/tokens/refresh_token
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
