name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight

concurrency:
  group: spotify-api-token

jobs:
  CI:
    runs-on: ubuntu-latest
    container:
      volumes:
        - /data:/data

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          tags: spotify-playlists-as-code:latest
          file: ./spotify-playlists-as-code/Dockerfile
          context: ./spotify-playlists-as-code
          load: true

      - name: Check formatting
        run: docker run spotify-playlists-as-code format:check

      - name: Lint
        run: docker run spotify-playlists-as-code lint

      - name: Create refresh token
        run: cp /data/refresh_token.txt ./docker/data/refresh_token.txt

      - name: Run healthcheck
        run: docker compose -f ./docker/docker-compose.healthcheck.yml up --exit-code-from spotify-playlists-as-code
        env:
          CLIENT_ID: ${{ vars.CLIENT_ID }}

      - name: Update refresh token secret
        if: always()
        run: cp ./docker/data/refresh_token.txt /data/refresh_token.txt
