name: Follow SPaC playlists

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *' # Every day at 1:00am

jobs:
  follow-spac-playlists:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create refresh token
        run: mkdir ./tokens && echo ${REFRESH_TOKEN} > ./tokens/refresh_token
        env:
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}

      - name: Follow SPaC playlists
        run: docker compose run spac follow
        env:
          CLIENT_ID: ${{ vars.CLIENT_ID }}

      - name: Update refresh token secret
        if: always()
        run: gh secret set REFRESH_TOKEN < ./tokens/refresh_token
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
