name: Follow SPaC playlists

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1-31/2 * *" # At 00:00 on every 2nd day-of-month from 1 through 31. https://crontab.guru/#0_0_1-31/2_*_*

concurrency:
  group: spotify-api-token

jobs:
  follow-spac-playlists:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create refresh token
        run: echo ${REFRESH_TOKEN} > ./data/tokens/refresh_token
        env:
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}

      - name: Follow SPaC playlists
        run: docker compose -f ./docker-compose.follow.yml up
        env:
          CLIENT_ID: ${{ vars.CLIENT_ID }}

      - name: Update refresh token secret
        if: always()
        run: gh secret set REFRESH_TOKEN < ./data/tokens/refresh_token
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
