name: Unfollow SPaC playlists

on:
  workflow_dispatch:

concurrency:
  group: spotify-api-token

jobs:
  unfollow-spac-playlists:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create refresh token
        run: echo ${REFRESH_TOKEN} > ./data/refresh_token
        env:
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}

      - name: Unfollow SPaC playlists
        run: docker compose -f ./docker/docker-compose.unfollow.yml up --exit-code-from spotify-playlists-as-code
        env:
          CLIENT_ID: ${{ vars.CLIENT_ID }}

      - name: Update refresh token secret
        if: always()
        run: gh secret set REFRESH_TOKEN < ./data/refresh_token
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
